# Mapping between pypi name and openEuler package name(without python prefix)
# Pypi name : openEuelr package name(without python prefix)
PYPI_OPENEULER_PKG_NAME_MAP = {
    "alabaster": "sphinx-theme-alabaster",
    "Babel": "babel",
    "Django": "Django",
    "dnspython": "dns",
    "Flask": "flask",
    "Flask-RESTful": "flask-restful",
    "Jinja2": "jinja2",
    "Mako": "mako",
    "MarkupSafe": "markupsafe",
    "oslosphinx": "oslo-sphinx",
    "ovs": "openvswitch",
    "Paste": "paste",
    "PasteDeploy": "paste-deploy",
    "Pillow": "pillow",
    "Pint": "pint",
    "prometheus-client": "prometheus_client",
    "Pygments": "pygments",
    "pyinotify": "inotify",
    "PyJWT": "jwt",
    "PyNaCl": "pynacl",
    "python-json-logger": "json_logger",
    "python-qpid-proton": "qpid-proton",
    "python-subunit": "subunit",
    "Routes": "routes",
    "Sphinx": "sphinx",
    "SQLAlchemy": "sqlalchemy",
    "semantic-version": "semantic_version",
    "Tempita": "tempita",
    "WebOb": "webob",
    "WebTest": "webtest",
    "Werkzeug": "werkzeug",
    "WSME": "wsme",
    "pyenchant": "enchant",
    "PyMySQL": "PyMySQL"
}


# Some libraries license doesn't correct in pypi. This Mapping fix them.
LICENSE_MAPPING = {
    "django-compressor": "Apache-2.0, MIT",
    "django-pyscss": "BSD",
    "jsonpath-rw-ext": "Apache-2.0",
    # This package is MIT in source code. But it shows "Apache" in pypi.
    "sqlalchemy-migrate": "MIT",
    "testresources": "Apache-2.0",
    "XStatic-Angular-FileUpload": "MIT",
    "XStatic-Angular-lrdragndrop": "MIT",
    "XStatic-Bootstrap-Datepicker": "Apache-2.0",
    "XStatic-Hogan": "Apache-2.0",
    "XStatic-Jasmine": "MIT",
    "XStatic-jQuery": "MIT",
    "XStatic-JQuery-Migrate": "MIT",
    "XStatic-jquery-ui": "MIT",
    "XStatic-JQuery.quicksearch": "MIT",
    "XStatic-JQuery.TableSorter": "MIT",
    "XStatic-mdi": "SIL OFL 1.1",
    "XStatic-Rickshaw": "MIT",
    "XStatic-smart-table": "MIT",
    "XStatic-Spin": "MIT",
    "XStatic-term.js": "MIT",
    "XStatic-tv4": "Public Domain",
    "URLObject": "Unlicense",
}
